import type { WeatherData } from './types';

export const DEFAULT_CITY = 'New York';

export const CITIES_WEATHER_DATA: WeatherData[] = [
  {
    city: 'New York',
    country: 'USA',
    currentTemp: 22,
    currentWeather: 'Partly cloudy',
    currentWeatherIcon: 'Partly cloudy',
    hourly: [
      { time: '3pm', temp: 22, icon: 'Partly cloudy' },
      { time: '4pm', temp: 21, icon: 'Partly cloudy' },
      { time: '5pm', temp: 20, icon: 'Cloudy' },
      { time: '6pm', temp: 19, icon: 'Cloudy' },
      { time: '7pm', temp: 18, icon: 'Cloudy' },
    ],
    daily: [
      { day: 'Today', high: 24, low: 18, icon: 'Partly cloudy', description: 'Mixed sun and clouds.' },
      { day: 'Tue', high: 26, low: 20, icon: 'Sunny', description: 'Clear skies.' },
      { day: 'Wed', high: 23, low: 17, icon: 'Rainy', description: 'Chance of showers.' },
      { day: 'Thu', high: 25, low: 19, icon: 'Sunny', description: 'Bright sunshine.' },
      { day: 'Fri', high: 22, low: 16, icon: 'Thunderstorm', description: 'Possible thunderstorms.' },
      { day: 'Sat', high: 27, low: 21, icon: 'Sunny', description: 'Very sunny.' },
      { day: 'Sun', high: 24, low: 18, icon: 'Partly cloudy', description: 'Partly cloudy skies.' },
    ],
    details: {
      humidity: 65,
      windSpeed: 15,
      uvIndex: 7,
      precipitation: 20,
    },
    lat: 40.7128,
    lng: -74.0060,
  },
  {
    city: 'London',
    country: 'UK',
    currentTemp: 18,
    currentWeather: 'Cloudy',
    currentWeatherIcon: 'Cloudy',
    hourly: [
      { time: '3pm', temp: 18, icon: 'Cloudy' },
      { time: '4pm', temp: 18, icon: 'Rainy' },
      { time: '5pm', temp: 17, icon: 'Rainy' },
      { time: '6pm', temp: 17, icon: 'Cloudy' },
      { time: '7pm', temp: 16, icon: 'Cloudy' },
    ],
    daily: [
      { day: 'Today', high: 20, low: 15, icon: 'Cloudy', description: 'Mostly overcast.' },
      { day: 'Tue', high: 22, low: 16, icon: 'Partly cloudy', description: 'A few sunny spells.' },
      { day: 'Wed', high: 19, low: 14, icon: 'Rainy', description: 'Persistent rain.' },
      { day: 'Thu', high: 21, low: 15, icon: 'Partly cloudy', description: 'Cloudy with sun.' },
      { day: 'Fri', high: 18, low: 13, icon: 'Rainy', description: 'Heavy showers expected.' },
      { day: 'Sat', high: 23, low: 17, icon: 'Sunny', description: 'Clear and sunny.' },
      { day: 'Sun', high: 20, low: 15, icon: 'Cloudy', description: 'Overcast skies.' },
    ],
    details: {
      humidity: 75,
      windSpeed: 20,
      uvIndex: 4,
      precipitation: 60,
    },
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    city: 'Tokyo',
    country: 'Japan',
    currentTemp: 28,
    currentWeather: 'Sunny',
    currentWeatherIcon: 'Sunny',
    hourly: [
      { time: '3pm', temp: 28, icon: 'Sunny' },
      { time: '4pm', temp: 27, icon: 'Sunny' },
      { time: '5pm', temp: 26, icon: 'Sunny' },
      { time: '6pm', temp: 25, icon: 'Clear' },
      { time: '7pm', temp: 24, icon: 'Clear' },
    ],
    daily: [
      { day: 'Today', high: 30, low: 24, icon: 'Sunny', description: 'Hot and sunny.' },
      { day: 'Tue', high: 31, low: 25, icon: 'Sunny', description: 'Very hot.' },
      { day: 'Wed', high: 28, low: 23, icon: 'Partly cloudy', description: 'Sunny intervals.' },
      { day: 'Thu', high: 29, low: 24, icon: 'Thunderstorm', description: 'Afternoon thunderstorms.' },
      { day: 'Fri', high: 30, low: 25, icon: 'Sunny', description: 'Clear skies.' },
      { day: 'Sat', high: 32, low: 26, icon: 'Sunny', description: 'Extremely hot.' },
      { day: 'Sun', high: 29, low: 24, icon: 'Rainy', description: 'Light showers.' },
    ],
    details: {
      humidity: 80,
      windSpeed: 10,
      uvIndex: 9,
      precipitation: 10,
    },
    lat: 35.6895,
    lng: 139.6917,
  },
];
