import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { getAuth, GoogleAuthProvider, type Auth } from 'firebase/auth';
import { getStorage, type FirebaseStorage } from 'firebase/storage';

// This configuration is auto-generated by Firebase.
// It's safe to expose this publicly, as security is enforced by server-side rules.
const firebaseConfig = {
    apiKey: "COLE_SUA_CHAVE_DE_API_DO_FIREBASE_AQUI",
    authDomain: "previs-o-master-americadosul.firebaseapp.com",
    projectId: "previs-o-master-americadosul",
    storageBucket: "previs-o-master-americadosul.appspot.com",
    messagingSenderId: "275898169040",
    appId: "1:275898169040:web:42a67e882c949c8286a111"
};

// Initialize variables that might be undefined
let app: FirebaseApp | undefined;
let db: Firestore | undefined;
let auth: Auth | undefined;
let storage: FirebaseStorage | undefined;
let googleProvider: GoogleAuthProvider | undefined;

// Verificação para garantir que a chave foi adicionada
if (firebaseConfig.apiKey && !firebaseConfig.apiKey.startsWith("COLE_SUA_CHAVE")) {
    try {
        app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
        db = getFirestore(app);
        auth = getAuth(app);
        storage = getStorage(app);
        googleProvider = new GoogleAuthProvider();
        googleProvider.addScope('https://www.googleapis.com/auth/userinfo.profile');
        googleProvider.addScope('https://www.googleapis.com/auth/userinfo.email');
    } catch(e) {
        console.error("Erro ao inicializar o Firebase. Verifique sua firebaseConfig:", e);
    }
} else {
    // This console.error will show up on the server during SSR and on the client.
    console.error("ERRO: A chave de API do Firebase não foi configurada. Edite o arquivo lib/firebase.ts. Os recursos do Firebase estão desativados.");
}

export { app, db, auth, storage, googleProvider };
