import { initializeApp, getApp, getApps } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth, GoogleAuthProvider } from 'firebase/auth';
import { getStorage } from 'firebase/storage';

// This configuration is auto-generated by Firebase.
// It's safe to expose this publicly, as security is enforced by server-side rules.
const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: "previs-o-master-americadosul.firebaseapp.com",
    projectId: "previs-o-master-americadosul",
    storageBucket: "previs-o-master-americadosul.appspot.com",
    messagingSenderId: "275898169040",
    appId: "1:275898169040:web:42a67e882c949c8286a111"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

const db = getFirestore(app);
const auth = getAuth(app);
const storage = getStorage(app);
const googleProvider = new GoogleAuthProvider();

googleProvider.addScope('https://www.googleapis.com/auth/userinfo.profile');
googleProvider.addScope('https://www.googleapis.com/auth/userinfo.email');

export { app, db, auth, storage, googleProvider };
