import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { getAuth, GoogleAuthProvider, type Auth } from 'firebase/auth';
import { getStorage, type FirebaseStorage } from 'firebase/storage';

// This configuration is auto-generated by Firebase.
// It's safe to expose this publicly, as security is enforced by server-side rules.
const firebaseConfig = {
  apiKey: "AIzaSyDXpvXAoC69-XKnq07d4FvImc2T3Mev9jM",
  authDomain: "studio-4398873450-7cc8f.firebaseapp.com",
  projectId: "studio-4398873450-7cc8f",
  storageBucket: "studio-4398873450-7cc8f.firebasestorage.app",
  messagingSenderId: "303740989273",
  appId: "1:303740989273:web:90dbad3598b2518219e648"
};

// Initialize variables that might be undefined
let app: FirebaseApp | undefined;
let db: Firestore | undefined;
let auth: Auth | undefined;
let storage: FirebaseStorage | undefined;
let googleProvider: GoogleAuthProvider | undefined;

// Verificação para garantir que a chave foi adicionada
if (firebaseConfig.apiKey && !firebaseConfig.apiKey.startsWith("COLE_SUA_CHAVE")) {
    try {
        app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
        db = getFirestore(app);
        auth = getAuth(app);
        storage = getStorage(app);
        googleProvider = new GoogleAuthProvider();
        googleProvider.addScope('https://www.googleapis.com/auth/userinfo.profile');
        googleProvider.addScope('https://www.googleapis.com/auth/userinfo.email');
    } catch(e) {
        console.error("Erro ao inicializar o Firebase. Verifique sua firebaseConfig:", e);
    }
} else {
    // This console.error will show up on the server during SSR and on the client.
    console.error("ERRO: A chave de API do Firebase não foi configurada. Edite o arquivo lib/firebase.ts. Os recursos do Firebase estão desativados.");
}

export { app, db, auth, storage, googleProvider };
