export type RadarThemeMode = 'classic' | 'gutoscope';

export interface ThemeColorMap {
  hex: string;
  r: number;
  g: number;
  b: number;
}

// Convert a hex string to RGB object
export function hexToRgb(hex: string): { r: number; g: number; b: number } {
  hex = hex.replace(/^#/, '');
  
  if (hex.length === 8) {
    hex = hex.substring(0, 6);
  }
  
  const bigint = parseInt(hex, 16);
  const r = (bigint >> 16) & 255;
  const g = (bigint >> 8) & 255;
  const b = bigint & 255;

  return { r, g, b };
}

// --- GutoScope Theme Colors ---

// REFLECTIVITY (dBZ)
// Mapping based on the table provided:
export const GUTOSCOPE_REFLECTIVITY: { threshold: number; color: ThemeColorMap }[] = [
  { threshold: 0, color: { hex: '#000000', r: 0, g: 0, b: 0 } }, // Transparent (alpha handled in code)
  { threshold: 5, color: { ...hexToRgb('#d6f0ff'), hex: '#d6f0ff' } },   // 0-5 Azul muito claro
  { threshold: 10, color: { ...hexToRgb('#a6d8ff'), hex: '#a6d8ff' } },  // 5-10 Azul claro
  { threshold: 15, color: { ...hexToRgb('#6fb8ff'), hex: '#6fb8ff' } },  // 10-15 Azul médio
  { threshold: 20, color: { ...hexToRgb('#3d8bff'), hex: '#3d8bff' } },  // 15-20 Azul forte
  { threshold: 25, color: { ...hexToRgb('#66ff66'), hex: '#66ff66' } },  // 20-25 Verde claro
  { threshold: 30, color: { ...hexToRgb('#33cc33'), hex: '#33cc33' } },  // 25-30 Verde
  { threshold: 35, color: { ...hexToRgb('#009900'), hex: '#009900' } },  // 30-35 Verde escuro
  { threshold: 40, color: { ...hexToRgb('#ffff66'), hex: '#ffff66' } },  // 35-40 Amarelo claro
  { threshold: 45, color: { ...hexToRgb('#ffcc33'), hex: '#ffcc33' } },  // 40-45 Amarelo
  { threshold: 50, color: { ...hexToRgb('#ff9933'), hex: '#ff9933' } },  // 45-50 Laranja
  { threshold: 55, color: { ...hexToRgb('#ff3333'), hex: '#ff3333' } },  // 50-55 Vermelho claro
  { threshold: 60, color: { ...hexToRgb('#cc0000'), hex: '#cc0000' } },  // 55-60 Vermelho
  { threshold: 65, color: { ...hexToRgb('#990000'), hex: '#990000' } },  // 60-65 Vermelho escuro
  { threshold: 70, color: { ...hexToRgb('#ff66cc'), hex: '#ff66cc' } },  // 65-70 Rosa
  { threshold: 75, color: { ...hexToRgb('#ff99ff'), hex: '#ff99ff' } },  // 70-75 Rosa claro
  { threshold: 100, color: { ...hexToRgb('#ffffff'), hex: '#ffffff' } }, // 75+ Branco
];

// VELOCITY (m/s)
// Mapping based on the table provided:
export const GUTOSCOPE_VELOCITY: { threshold: number; color: ThemeColorMap }[] = [
  { threshold: -60, color: { ...hexToRgb('#5a00a3'), hex: '#5a00a3' } }, // Roxo escuro
  { threshold: -50, color: { ...hexToRgb('#7a00cc'), hex: '#7a00cc' } }, // Roxo
  { threshold: -40, color: { ...hexToRgb('#0033cc'), hex: '#0033cc' } }, // Azul escuro
  { threshold: -30, color: { ...hexToRgb('#0066ff'), hex: '#0066ff' } }, // Azul
  { threshold: -20, color: { ...hexToRgb('#33ccff'), hex: '#33ccff' } }, // Azul claro
  { threshold: -10, color: { ...hexToRgb('#66ff99'), hex: '#66ff99' } }, // Verde claro
  { threshold: -5,  color: { ...hexToRgb('#ccffcc'), hex: '#ccffcc' } }, // Verde muito claro
  { threshold: 0,   color: { ...hexToRgb('#cccccc'), hex: '#cccccc' } }, // Cinza neutro
  { threshold: 5,   color: { ...hexToRgb('#ffcccc'), hex: '#ffcccc' } }, // Vermelho muito claro
  { threshold: 10,  color: { ...hexToRgb('#ff9999'), hex: '#ff9999' } }, // Vermelho claro
  { threshold: 20,  color: { ...hexToRgb('#ff3333'), hex: '#ff3333' } }, // Vermelho
  { threshold: 30,  color: { ...hexToRgb('#cc0000'), hex: '#cc0000' } }, // Vermelho forte
  { threshold: 40,  color: { ...hexToRgb('#990000'), hex: '#990000' } }, // Vinho
  { threshold: 50,  color: { ...hexToRgb('#cc0066'), hex: '#cc0066' } }, // Magenta
  { threshold: 60,  color: { ...hexToRgb('#ff00cc'), hex: '#ff00cc' } }, // Rosa/roxo
];

export const CLASSIC_REFLECTIVITY_COLORS = [
  // This is a rough mapping of the Classic colors currently generated by the CPTEC/Redemet maps
  // to map them to the new dBZ indices.
  { r: 0, g: 255, b: 255, dBZ: 5 },     // Cyan
  { r: 0, g: 153, b: 255, dBZ: 10 },
  { r: 0, g: 0, b: 255, dBZ: 15 },      // Blue
  { r: 0, g: 255, b: 0, dBZ: 20 },      // Light green
  { r: 0, g: 204, b: 0, dBZ: 25 },
  { r: 0, g: 153, b: 0, dBZ: 30 },      // Green
  { r: 255, g: 255, b: 0, dBZ: 35 },    // Yellow
  { r: 255, g: 204, b: 0, dBZ: 40 },
  { r: 255, g: 153, b: 0, dBZ: 45 },    // Orange
  { r: 255, g: 0, b: 0, dBZ: 50 },      // Red
  { r: 204, g: 0, b: 0, dBZ: 55 },
  { r: 153, g: 0, b: 0, dBZ: 60 },      // Dark Red
  { r: 255, g: 0, b: 255, dBZ: 65 },    // Magenta/Pink
  { r: 153, g: 0, b: 255, dBZ: 70 },    // Purple
  { r: 255, g: 255, b: 255, dBZ: 75 }   // White
];

export const CLASSIC_VELOCITY_COLORS = [
  // Negative (Approaching usually, or away depending on convention. Here we follow your table)
  { r: 0, g: 0, b: 153, vel: -40 },
  { r: 0, g: 0, b: 255, vel: -30 },
  { r: 0, g: 153, b: 255, vel: -20 },
  { r: 0, g: 255, b: 255, vel: -10 },
  
  // Zeroish
  { r: 200, g: 200, b: 200, vel: 0 },
  
  // Positive
  { r: 255, g: 255, b: 0, vel: 10 },
  { r: 255, g: 153, b: 0, vel: 20 },
  { r: 255, g: 0, b: 0, vel: 30 },
  { r: 153, g: 0, b: 0, vel: 40 },
  { r: 255, g: 0, b: 255, vel: 50 },
];
